In [7]:
import numpy as np
x = np.array(range(24))
y = x.reshape((3,4,2),order='C')
print(y)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [12]:
import numpy as np
x = np.array([2,5,18,14,4])
y = x[:,np.newaxis]
print(y)
print("\n")
x = np.arange(6)
y = x.reshape(2,3)
print(y[:,np.newaxis])

[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]


[[[0 1 2]]

 [[3 4 5]]]


In [13]:
x=np.array([[1,2],[3,4]])
np.tile(x,(3,4))

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [16]:
import numpy as np

a = np.array([3,4,5])
b = np.array([1,9,0])
print(np.row_stack((a,b)))
print(np.column_stack((a,b)))
print(np.shape(a))

[[3 4 5]
 [1 9 0]]
[[3 1]
 [4 9]
 [5 0]]
(3,)


In [24]:
import numpy as np
a = np.array([4,7,3,4,2,8])
c = (a==4)
print(c,type(c))

lt = (a<5)
print(lt,type(lt))

x = np.array([1,2,3,4,5,6,7])
c = x>3
x[c]=0
x

[ True False False  True False False] <class 'numpy.ndarray'>
[ True False  True  True  True False] <class 'numpy.ndarray'>


array([1, 2, 3, 0, 0, 0, 0])

In [27]:
import numpy as np

b= np.array([[142,56,189,65],
             [299,288,10,12],
             [55,142,17,18]])

e0 = np.array([0,0,0,0])
e1 = np.array([0,3,2,1])

f = b[(e0,e1)]

print(f)

[142  65 189  56]


In [121]:
import numpy as np
aa_milne_arr = ['a','b','c','d']

print(np.random.choice(aa_milne_arr,1,p=[0.6,0.1,0.1,0.2]))

['a']


In [128]:
from pandas import Series, DataFrame
import pandas as pd

obj = Series([4,7,-5,3])
obj.index

RangeIndex(start=0, stop=4, step=1)

In [161]:
from pandas import Series, DataFrame
data = {'city':['seoul','seoul','seoul','daegu','daegu'],
        'year':[2010,2011,2012,2011,2012],
        'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(data)
frame
frame2 = DataFrame(data,columns=['year','city','pop','debt'],
                   index=['one','two','three','four','five'])

frame2['city']
frame2['year']

frame2.ix['three']

frame2['debt'] = np.arange(5.)

frame2

val = Series([-1.2,-1.5,-1.7],index=['two','four','five'])

frame2['debt'] = val

frame2

frame2['eastern'] = frame2.city =='daegu'

frame2

c:\python37\lib\site-packages\ipykernel_launcher.py:13: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  del sys.path[0]


year   city  pop  debt  eastern
one    2010  seoul  1.5   NaN    False
two    2011  seoul  1.7  -1.2    False
three  2012  seoul  3.6   NaN    False
four   2011  daegu  2.4  -1.5     True
five   2012  daegu  2.9  -1.7     True

In [164]:
del frame2['eastern']
frame2.columns

pop = {'daegu':{2011:2.4,2012:2.9},'seoul':{2010:1.5,2011:1.7,2012:3.6}}
frame3 = DataFrame(pop)

SyntaxError: invalid syntax (<ipython-input-164-ab901b29c289>, line 1)

In [165]:
obj3 = Series(['blue','purple','yellow'], index=[0,2,4])

obj3.reindex(range(6),method='ffill')


0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [184]:
obj = Series(np.arange(5.0),index=['a','b','c','d','e'])
new_obj = obj.drop('c')
new_obj
obj.drop(['d','c'])
data = DataFrame(np.arange(16).reshape((4,4)),
                index=['daegu','sejong','daejeon','incheon'],
                columns=['one','two','three','four'])

data[:2]
data[data['three']>5]
data<5


one    two  three   four
daegu     True   True   True   True
sejong    True  False  False  False
daejeon  False  False  False  False
incheon  False  False  False  False

In [185]:
frame = DataFrame(np.random.randn(4,3),columns=list('bde'),index=['utah','ohio','texas','oregon'])

frame

b         d         e
utah   -0.464661  0.526740 -0.442873
ohio   -0.927089  1.345158  2.382178
texas   0.068732  0.195570 -1.349628
oregon  1.258151  0.653757  1.427635

In [186]:
np.abs(frame)

b         d         e
utah    0.464661  0.526740  0.442873
ohio    0.927089  1.345158  2.382178
texas   0.068732  0.195570  1.349628
oregon  1.258151  0.653757  1.427635

In [187]:
f= lambda x:x.max()-x.min()
frame.apply(f)

b    2.185241
d    1.149587
e    3.731806
dtype: float64

In [188]:
frame.apply(f,axis=1)

utah      0.991401
ohio      3.309267
texas     1.545199
oregon    0.773877
dtype: float64

In [6]:
from pandas import Series, DataFrame
import pandas as pd

df = DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3],[0.75,-1.3]],
               index=['a','b','c','d','e'], columns=['one','two'])

df
df.sum(axis=1)
df.mean(axis=1,skipna=False)

NameError: name 'np' is not defined

In [207]:
data = Series(np.random.randn(10), index=[['a','a','a','b','b','b','c','c','d','d'],[1,2,3,1,2,3,1,2,2,3]])
data
data.index
data['b']
data.ix[['b','d']]
data.unstack().stack()

c:\python37\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """


a  1    1.240052
   2   -0.389241
   3   -0.531158
b  1   -0.255674
   2    0.460433
   3    1.211166
c  1   -1.238578
   2    0.456108
d  2    0.635224
   3   -0.198297
dtype: float64

In [208]:
df1 = pd.read_clipboard()
df1

earn     height     sex  ed  age      race
0   50000  74.424439    male  16   45     white
1   60000  65.537543  female  16   58     white
2   30000  63.629198  female  16   29     white
3   50000  63.108562  female  16   91     other
4   51000  63.402484  female  17   39     white
5    9000  64.399508  female  15   26     white
6   29000  61.656326  female  12   49     white
7   32000  72.698544    male  17   46     white
8    2000  72.039467    male  15   21  hispanic
9   27000  72.234933    male  12   26     white
10   6530  69.512146    male  16   65     white

In [216]:
df2 = pd.read_csv("동별 연령별 한국인 현황(2015년).csv",engine='python')
df2.head()

연령 동구 충장동_남 동구 충장동_여 동구 동명동_남 동구 동명동_여 동구 계림1동_남 동구 계림1동_여 동구 계림2동_남  \
0   0 세        9        8        9       13        21        21        26   
1   1 세       11        7       17       12        26        19        41   
2   2 세        8        8       12       11        22        23        32   
3   3 세       12        6       11        7        18        25        43   
4   4 세        6        5       13        5        19        17        37   

  동구 계림2동_여 동구 산수1동_남  ... 광산구 임곡동_남 광산구 임곡동_여 광산구 동곡동_남 광산구 동곡동_여 광산구 평동_남  \
0        23        26  ...       4.0       2.0       1.0       2.0     10.0   
1        22        17  ...       1.0       3.0       NaN       1.0      9.0   
2        38        27  ...       4.0       6.0       4.0       4.0      9.0   
3        27        28  ...       9.0       6.0       2.0       NaN      6.0   
4        40        28  ...       1.0       NaN       2.0       3.0      7.0   

  광산구 평동_여 광산구 삼도동_남 광산구 삼도동_여 광산구 본량동_남 광산구 본량동_여  
0      3.0       4.0       5.0       2.0       2.0  
1      5.0       3.0       5.0       2.0       2.0  
2      2.0       4.0       3.0       2.0       4.0  
3      3.0       5.0       5.0       3.0       3.0  
4      4.0       3.0       4.0       1.0       3.0  

[5 rows x 191 columns]

In [218]:
df2.tail(3)

연령 동구 충장동_남 동구 충장동_여 동구 동명동_남 동구 동명동_여 동구 계림1동_남 동구 계림1동_여 동구 계림2동_남  \
98    98 세       -        -        -        -          1        -          1   
99    99 세       -        -        -        -         -          2        -    
100   100+       -         2       -         5        -          5         1   

    동구 계림2동_여 동구 산수1동_남  ... 광산구 임곡동_남 광산구 임곡동_여 광산구 동곡동_남 광산구 동곡동_여 광산구 평동_남  \
98          1        -   ...       NaN       NaN       NaN       NaN      NaN   
99          1        -   ...       NaN       1.0       NaN       NaN      NaN   
100        -         -   ...       NaN       NaN       1.0       2.0      NaN   

    광산구 평동_여 광산구 삼도동_남 광산구 삼도동_여 광산구 본량동_남 광산구 본량동_여  
98       NaN       NaN       NaN       NaN       1.0  
99       NaN       NaN       NaN       NaN       1.0  
100      2.0       1.0       2.0       NaN       2.0  

[3 rows x 191 columns]

In [222]:
df2.columns.names = ["광주지역 남여"]
df2.index.names = ["나이"]
df2.isna().sum().sum()

215

In [223]:
df2.fillna(0)

광주지역 남여     연령 동구 충장동_남 동구 충장동_여 동구 동명동_남 동구 동명동_여 동구 계림1동_남 동구 계림1동_여  \
나이                                                                       
0          0 세        9        8        9       13        21        21   
1          1 세       11        7       17       12        26        19   
2          2 세        8        8       12       11        22        23   
3          3 세       12        6       11        7        18        25   
4          4 세        6        5       13        5        19        17   
5          5 세        8        7       12       12        18        14   
6          6 세        6        3       11        5        25        13   
7          7 세        1        8       17        6        14        13   
8          8 세       10        4        6       11        13        16   
9          9 세        9        4        9        8        12        17   
10        10 세        3        5        7        8        16        14   
11        11 세       11        6       16       13        25        15   
12        12 세        4        9       14       10        16        15   
13        13 세        9        9       16       17        18        28   
14        14 세       11       14       19       13        30        18   
15        15 세       16       13       25       22        41        30   
16        16 세       13       18       18       15        44        31   
17        17 세       14       14       19       23        39        33   
18        18 세       21       25       21       24        42        32   
19        19 세       18       23       22       20        41        40   
20        20 세       15       27       24       31        39        53   
21        21 세       32       20       29       30        64        42   
22        22 세       22       41       36       31        39        51   
23        23 세       32       35       38       39        61        50   
24        24 세       28       54       37       35        47        42   
25        25 세       39       37       51       41        55        42   
26        26 세       36       46       47       33        59        54   
27        27 세       49       42       31       24        39        46   
28        28 세       39       42       36       33        44        65   
29        29 세       35       44       52       31        66        44   
..         ...      ...      ...      ...      ...       ...       ...   
71        71 세       31       33       26       30        41        45   
72        72 세       29       24       24       30        46        41   
73        73 세       44       22       29       46        67        72   
74        74 세       32       27       30       36        39        50   
75        75 세       24       16       28       19        28        29   
76        76 세       16       17       21       25        39        25   
77        77 세       23       16       27       22        41        30   
78        78 세       17       12       18       16        18        35   
79        79 세       12       11       17       18        28        30   
80        80 세       12       13       16       22        21        33   
81        81 세       14       16       15       22        15        25   
82        82 세       11        9       11       19        11        21   
83        83 세       10       15        7       13         9        23   
84        84 세        4        5       10       13        10        14   
85        85 세        5       10        3       14         4        16   
86        86 세        6       14        6       10         3        15   
87        87 세        2        6        8       14         3         2   
88        88 세        3        8        2        7         7        13   
89        89 세        1        6        2        9         7         5   
90        90 세        2        5        1        3         3         5   
91        91 세       -         5        3        3         1         6   
92  

In [9]:
df1 = pd.read_clipboard()
df1.set_index(['ed','age'])
df1.reset_index()

index   earn     height     sex  ed  age      race
0       0  50000  74.424439    male  16   45     white
1       1  60000  65.537543  female  16   58     white
2       2  30000  63.629198  female  16   29     white
3       3  50000  63.108562  female  16   91     other
4       4  51000  63.402484  female  17   39     white
5       5   9000  64.399508  female  15   26     white
6       6  29000  61.656326  female  12   49     white
7       7  32000  72.698544    male  17   46     white
8       8   2000  72.039467    male  15   21  hispanic
9       9  27000  72.234933    male  12   26     white
10     10   6530  69.512146    male  16   65     white

In [18]:
data = pd.read_csv("동별 연령별 한국인 현황(2015년).csv",engine='python')
data.to_pickle('frame_pickle')
pd.read_pickle('frame_pickle')

연령 동구 충장동_남 동구 충장동_여 동구 동명동_남 동구 동명동_여 동구 계림1동_남 동구 계림1동_여 동구 계림2동_남  \
0      0 세        9        8        9       13        21        21        26   
1      1 세       11        7       17       12        26        19        41   
2      2 세        8        8       12       11        22        23        32   
3      3 세       12        6       11        7        18        25        43   
4      4 세        6        5       13        5        19        17        37   
5      5 세        8        7       12       12        18        14        43   
6      6 세        6        3       11        5        25        13        42   
7      7 세        1        8       17        6        14        13        35   
8      8 세       10        4        6       11        13        16        42   
9      9 세        9        4        9        8        12        17        38   
10    10 세        3        5        7        8        16        14        47   
11    11 세       11        6       16       13        25        15        39   
12    12 세        4        9       14       10        16        15        50   
13    13 세        9        9       16       17        18        28        43   
14    14 세       11       14       19       13        30        18        73   
15    15 세       16       13       25       22        41        30        66   
16    16 세       13       18       18       15        44        31        60   
17    17 세       14       14       19       23        39        33        79   
18    18 세       21       25       21       24        42        32        76   
19    19 세       18       23       22       20        41        40        55   
20    20 세       15       27       24       31        39        53        73   
21    21 세       32       20       29       30        64        42        90   
22    22 세       22       41       36       31        39        51        80   
23    23 세       32       35       38       39        61        50        71   
24    24 세       28       54       37       35        47        42        75   
25    25 세       39       37       51       41        55        42        63   
26    26 세       36       46       47       33        59        54        55   
27    27 세       49       42       31       24        39        46        51   
28    28 세       39       42       36       33        44        65        53   
29    29 세       35       44       52       31        66        44        49   
..     ...      ...      ...      ...      ...       ...       ...       ...   
71    71 세       31       33       26       30        41        45        45   
72    72 세       29       24       24       30        46        41        47   
73    73 세       44       22       29       46        67        72        60   
74    74 세       32       27       30       36        39        50        50   
75    75 세       24       16       28       19        28        29        52   
76    76 세       16       17       21       25        39        25        29   
77    77 세       23       16       27       22        41        30        36   
78    78 세       17       12       18       16        18        35        39   
79    79 세       12       11       17       18        28        30        35   
80    80 세       12       13       16       22        21        33        13   
81    81 세       14       16       15       22        15        25        25   
82    82 세       11        9       11       19        11        21        13   
83    83 세       10       15        7       13         9        23        14   
84    84 세        4        5       10       13        10        14        12   
85    85 세        5       10        3       14         4        16        10   
86    86 세        6       14        6       10         3        15         8   
87    87 세        2        6        8       14         3         2         7   
88    88 세        3        8        2        7         7        13         6   
89    89